[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ["node_modules", "lib"]
test = 'test/foundry'
script = 'scripts/foundry'
gas_reports = ["*"]
optimizer_runs = 1000

remappings = [
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config