/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HackCoinFlip__factory } from "./HackCoinFlip__factory";
export { HackTelephone__factory } from "./HackTelephone__factory";
