/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CoinFlip } from "./CoinFlip";
export type { King } from "./King";
export type { Telephone } from "./Telephone";
